// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtAGm-4Oav8ESih7TXKzwQA-HDMeEm1m4',
    appId: '1:403733991988:web:78c7a99642953367d27061',
    messagingSenderId: '403733991988',
    projectId: 'wall-9f20f',
    authDomain: 'wall-9f20f.firebaseapp.com',
    storageBucket: 'wall-9f20f.appspot.com',
    measurementId: 'G-K8QJM0BW4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxLuZfXKsLATYx33_IE20i3PGsTiHzpyQ',
    appId: '1:403733991988:android:8bc1e4b33e729322d27061',
    messagingSenderId: '403733991988',
    projectId: 'wall-9f20f',
    storageBucket: 'wall-9f20f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwb85nPB-e4ALOZSXXC0o-obS1XTV35WQ',
    appId: '1:403733991988:ios:b9ce1c1c0496cb31d27061',
    messagingSenderId: '403733991988',
    projectId: 'wall-9f20f',
    storageBucket: 'wall-9f20f.appspot.com',
    iosClientId: '403733991988-9n11nmnb5n8qh1cj7cpqfve8k9l5mfg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.wall',
  );

}